compra/urls.py
from django.urls import path
from .views import carrito, agregar_producto, eliminar_producto, restar_producto, limpiar_carrito
from django.conf import settings

app_name = "compra"

urlpatterns = [
        path('carrito/', carrito, name="carrito"),
        path('agregar/', agregar_producto, name="agregar"),
        path('eliminar/<int:producto_id>/', eliminar_producto, name="eliminar"),
        path('restar/<int:producto_id>/', restar_producto, name="restar"),
        path('limpiar/', limpiar_carrito, name="limpiar"),
]

pago/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'pago'

urlpatterns = [
    path('realizar-compra/', views.create_order, name='create_order'),
    path('confirmacion/<int:compra_id>/', views.confirmacion_compra, name='confirmacion'),
    path(
        "webhooks/paygreen/mPnBRC1qxapOAxQpWmjy4NofbgxCmXSj/",
        views.paygreen_webhook,
    ),
    path('prueba-order/', views.prueba_order, name='prueba_order'),
    path('cancelacion/<int:compra_id>/', views.cancelacion_compra, name="cancelacion",)
]

tienda/urls.py
from django.urls import path
from .views import PrincipalView, CategoriasView, ProductoDetailView
from django.views.generic.base import RedirectView
from django.templatetags.static import static

app_name = "tienda"

urlpatterns = [
    path('', PrincipalView.as_view(), name="home"),
    path('productos/', CategoriasView.as_view(), name='listado'),
    path('productos/<slug:slug>/', ProductoDetailView.as_view(), name='detalle'),
    path('favicon.ico',RedirectView.as_view(url=static('favicon.ico'))),
]

tiendacbd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('tienda.urls')),
    path('compra/', include('compra.urls')),
    path('pago/', include('pago.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

compra/models.py
from django.db import models

# Create your models here.

compra/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from tienda.models import Producto, Precio_stock
from django.http.response import JsonResponse
from django.urls import reverse
from django.conf import settings
from compra.carrito import Carrito

# Create your views here.
def carrito(request):
    carrito = Carrito(request)
    return render(request, "compra/carrito.html", {"carrito": carrito})

def agregar_producto(request):
    if request.method == 'POST':
        producto_id = request.POST.get('producto_id')
        carrito = Carrito(request)
        producto = Precio_stock.objects.get(id=producto_id)
        carrito.agregar(producto)
        return redirect("compra:carrito")

def eliminar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Precio_stock.objects.get(id=producto_id)
    carrito.eliminar(producto)
    return redirect("compra:carrito")

def restar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Precio_stock.objects.get(id=producto_id)
    carrito.restar(producto)
    return redirect("compra:carrito")

def limpiar_carrito(request):
    carrito = Carrito(request)
    carrito.limpiar()
    return redirect("compra:carrito")

compra/templates/compra/carrito.html
{% extends 'pages/base.html' %}
{% block navbar %}
{% include 'pages/navbar.html' %}
{% endblock navbar %}
{% block content %}
<h2>Productos en el carrito:</h2>
{% if carrito %}
  <ul class="list-unstyled">
    {% for producto_id, producto_data in carrito.carrito.items %}
      <li class="mb-3">
        <div class="d-flex align-items-center">
          <div class="mr-3">
            <!-- Agrega aquí la imagen a la izquierda -->
            <a href="{% url 'tienda:detalle' slug=producto_data.link %}">
            <img src="{{ producto_data.foto }}" alt="Imagen del producto" width="100" height="75">
          </a>
          </div>
          <div>
            <strong>Nombre del Producto:</strong> {{ producto_data.name }}<br>
            <strong>Precio:</strong> ${{ producto_data.precio }}<br>
            <strong>Cantidad:</strong> {{ producto_data.quantity }}
          </div>
          <form action="{% url 'compra:eliminar' producto_id=producto_id %}" method="post" class="ml-auto">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
          </form>
          <form action="{% url 'compra:restar' producto_id=producto_id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-secondary btn-sm">-</button>
          </form>
          <form action="{% url 'compra:agregar' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="producto_id" value="{{ producto_id }}">
            {% if producto_data.stock > producto_data.quantity %}
              <button type="submit" class="btn btn-success btn-sm">+</button>
            {% else %}
              <button type="button" class="btn btn-success btn-sm" disabled>+<span class="text-danger"> Límite de stock</span></button>
            {% endif %}
          </form>
        </div>
      </li>
    {% endfor %}
  </ul>
  {% if carrito.carrito.items %}
  <p>Total del Carrito: ${{ carrito_total }}</p>

  <a href="{% url 'pago:create_order' %}" class="btn btn-primary">Pagar</a>
  <a href="{% url 'pago:prueba_order' %}" class="btn btn-primary">Probar</a>

  <a href="{% url 'tienda:listado' %}" class="btn btn-secondary">Volver a la tienda</a>
{% else %}
  <p>No hay productos en el carrito.</p>
  <a href="{% url 'tienda:listado' %}" class="btn btn-secondary">Volver a la tienda</a>
  {% endif %}
{% endif %}
{% endblock content %}