compra/urls.py
from django.urls import path
from .views import carrito, agregar_producto, eliminar_producto, restar_producto, limpiar_carrito
from django.conf import settings

app_name = "compra"

urlpatterns = [
        path('carrito/', carrito, name="carrito"),
        path('agregar/', agregar_producto, name="agregar"),
        path('eliminar/<int:producto_id>/', eliminar_producto, name="eliminar"),
        path('restar/<int:producto_id>/', restar_producto, name="restar"),
        path('limpiar/', limpiar_carrito, name="limpiar"),
]

pago/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'pago'

urlpatterns = [
    path('realizar-compra/', views.create_order, name='create_order'),
    path('confirmacion/<int:compra_id>/', views.confirmacion_compra, name='confirmacion'),
    path(
        "webhooks/paygreen/mPnBRC1qxapOAxQpWmjy4NofbgxCmXSj/",
        views.paygreen_webhook,
    ),
    path('prueba-order/', views.prueba_order, name='prueba_order'),
    path('cancelacion/<int:compra_id>/', views.cancelacion_compra, name="cancelacion",)
]

tienda/urls.py
from django.urls import path
from .views import PrincipalView, CategoriasView, ProductoDetailView
from django.views.generic.base import RedirectView
from django.templatetags.static import static

app_name = "tienda"

urlpatterns = [
    path('', PrincipalView.as_view(), name="home"),
    path('productos/', CategoriasView.as_view(), name='listado'),
    path('productos/<slug:slug>/', ProductoDetailView.as_view(), name='detalle'),
    path('favicon.ico',RedirectView.as_view(url=static('favicon.ico'))),
]

tiendacbd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('tienda.urls')),
    path('compra/', include('compra.urls')),
    path('pago/', include('pago.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/pages/base.html
{% load static %}
<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">

    <!-- Style -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    {% block extrahead %}

    {% endblock extrahead %}
    <!--Bootstrap 5.3v-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>
</head>
  <body {% block body_class %} {% endblock body_class %}>
    {% block navbar %}{% endblock navbar %}

    {# % include 'messages.html' % #}
    {% block content %}
    {% endblock content %}

    {% block footer %}
    {% endblock footer %}

    {% block javascript %}{% endblock javascript %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

templates/pages/navbar.html
{% load static %}

<!-- Cabecera para móviles con RRSS -->
<div class="site-mobile-menu site-navbar-target">
  <div class="site-mobile-menu-header">
    <div class="site-mobile-menu-close mt-3">
      <span class="icon-close2 js-menu-toggle"></span>
    </div>
  </div>
  <div class="site-mobile-menu-body"></div>
</div>


<div class="top-bar bg-warning">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <a href="#" class=""><span class="mr-2  icon-envelope-open-o"></span> <span class="d-none d-md-inline-block">test@tiendaCBD.com</span></a>
        <span class="mx-md-2 d-inline-block"></span>
        <a href="#" class=""><span class="mr-2  icon-phone"></span> <span class="d-none d-md-inline-block">943 43 43 43</span></a>
        <a href="#" class="float-right"><span class="mr-2  icon-twitter"></span> <span class="d-none d-md-inline-block">Twitter</span></a>
        <span class="mx-md-2 d-inline-block"></span>
        <a href="#" class="float-right"><span class="mr-2  icon-facebook"></span> <span class="d-none d-md-inline-block">Facebook</span></a>

      </div>

    </div>

  </div>
</div>

</div>
  </div>
          <!-- Navigation-->
          <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top mb-0 p-0">
            <div class="container-fluid px-4 px-lg-5" style="background-color: #bfff00;">
                <a class="navbar-brand" href="{% url 'tienda:home' %}">La Revolución Verde CBD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-lg-2 mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'tienda:home'%}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'tienda:listado'%}">Listado de productos</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Sobre nosotros</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categorías</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <li><a class="dropdown-item" href="{% url 'tienda:listado'%}">Todos los productos</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'tienda:listado'%?categoria=FLORES}">Flores</a></li>
                                <li><a class="dropdown-item" href="{% url 'tienda:listado'%}?categoria=COSMÉTICOS">Cosméticos</a></li>
                                <li><a class="dropdown-item" href="{% url 'tienda:listado'%}?categoria=ROPA">Ropa</a></li>
                                <li><a class="dropdown-item" href="{% url 'tienda:listado'%}?categoria=COMESTIBLES">Comestibles</a></li>
                                <li><a class="dropdown-item" href="{% url 'tienda:listado'%}?categoria=VARIOS">Varios</a></li>
                            </ul>
                        </li>
                    </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"></li>
                      <form class="d-flex" action="{% url 'compra:carrito' %}">
                        <button class="btn btn-outline-dark" type="submit">
                          <i class="bi-cart-fill me-1"></i>
                          Carrito
                          <span class="badge bg-dark text-white ms-1 rounded-pill">{{ request.session.carrito|length }}</span>
                        </button>
                      </form>
                    </li>
                  <li class="nav-item">
                    {% if user.is_authenticated %}
                      <a class="btn btn-success green-button" href="{% url 'account_email' %}">Cambiar e-mail</a>
                      <a class="btn btn-success green-button" href="{% url 'account_logout' %}" role="button">Logout</a>
                    {% else %}
                      <a class="btn btn-success green-button" href="{% url 'account_login' %}" role="button">Entrar</a>
                      <a class="btn btn-success green-button" href="{% url 'account_signup' %}" role="button">Registrarse</a>
                    {% endif %}
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        
        </div>
        </div>
</header>